import { Request, Response, NextFunction } from "express";
import { ZodSchema } from "zod";
import { badRequest } from "../utils/api-error.js";

/**
 * ============================================================================
 * DESIGN PATTERN: Middleware Factory (Higher-Order Function)
 *
 * For every incoming API request, we want to validate the request body with a
 * different Zod schema. Hence, we need separate middleware for each route
 * that requires validation.
 *
 * This is a higher-order function that takes a Zod schema as an argument and
 * returns a new middleware function custom for that schema.
 * ============================================================================
 */
export const validate = (schema: ZodSchema) => {
  // This is the actual Express middleware function generated by the factory
  return (req: Request, _res: Response, next: NextFunction) => {
    const result = schema.safeParse(req.body);

    if (!result.success) {
      throw badRequest("Validation failed", result.error.issues);
    }

    req.body = result.data; // This is the parsed and validated data

    // If successful, pass the request to the next step (the Controller)
    next();
  };
};
